export { default as Pricing } from "./Pricing";
export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Logo } from "./Logo";
export { default as Testimonials } from "./Testimonials";
export { default as Footer } from "./Footer";
export { default as Brand } from "./Brand";
export { default as Features } from "./Features";
export { default as SideNav } from "./SideNav";
